// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCTVocabulary.Models;

#nullable disable

namespace TCTVocabulary.Migrations
{
    [DbContext(typeof(DbflashcardContext))]
    partial class DbflashcardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassMember", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ClassId", "UserId")
                        .HasName("PK__ClassMem__1A61AB6A6D3064A5");

                    b.HasIndex("UserId");

                    b.ToTable("ClassMembers", (string)null);
                });

            modelBuilder.Entity("TCTVocabulary.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetId")
                        .HasColumnType("int")
                        .HasColumnName("SetID");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CardId")
                        .HasName("PK__Cards__55FECD8E2103FA66");

                    b.HasIndex("SetId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927A0B52422EC");

                    b.HasIndex("OwnerId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FolderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderId"));

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("int")
                        .HasColumnName("ParentFolderID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FolderId")
                        .HasName("PK__Folders__ACD7109F2ECFF2AF");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("UserId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("TCTVocabulary.Models.LearningProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardID");

                    b.Property<DateTime?>("LastReviewedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("WrongCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProgressId")
                        .HasName("PK__Learning__BAE29C8531677C23");

                    b.HasIndex("CardId");

                    b.HasIndex(new[] { "UserId", "CardId" }, "UQ__Learning__E2D72075740E222A")
                        .IsUnique();

                    b.ToTable("LearningProgress", (string)null);
                });

            modelBuilder.Entity("TCTVocabulary.Models.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int")
                        .HasColumnName("FolderID");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SetId")
                        .HasName("PK__Sets__7E08473D47BDA11E");

                    b.HasIndex("FolderId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("TCTVocabulary.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Goal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC46CDCFCA");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534362A84D8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClassMember", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassMemb__Class__440B1D61");

                    b.HasOne("TCTVocabulary.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ClassMemb__UserI__44FF419A");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Card", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Set", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .IsRequired()
                        .HasConstraintName("FK__Cards__SetID__4CA06362");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Class", b =>
                {
                    b.HasOne("TCTVocabulary.Models.User", "Owner")
                        .WithMany("Classes")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__OwnerID__412EB0B6");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Folder", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Folder", "ParentFolder")
                        .WithMany("InverseParentFolder")
                        .HasForeignKey("ParentFolderId")
                        .HasConstraintName("FK__Folders__ParentF__3E52440B");

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("Folders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Folders__UserID__3D5E1FD2");

                    b.Navigation("ParentFolder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.LearningProgress", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Card", "Card")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK__LearningP__CardI__5441852A");

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__LearningP__UserI__534D60F1");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Set", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Folder", "Folder")
                        .WithMany("Sets")
                        .HasForeignKey("FolderId")
                        .HasConstraintName("FK__Sets__FolderID__49C3F6B7");

                    b.HasOne("TCTVocabulary.Models.User", "Owner")
                        .WithMany("Sets")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Sets__OwnerID__48CFD27E");

                    b.Navigation("Folder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Card", b =>
                {
                    b.Navigation("LearningProgresses");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Folder", b =>
                {
                    b.Navigation("InverseParentFolder");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Set", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("TCTVocabulary.Models.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Folders");

                    b.Navigation("LearningProgresses");

                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
