// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCTVocabulary.Models;

#nullable disable

namespace TCTVocabulary.Migrations
{
    [DbContext(typeof(DbflashcardContext))]
    [Migration("20260306183151_AddRepetitionCountToLearningProgress")]
    partial class AddRepetitionCountToLearningProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClassMember", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ClassId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ClassMembers", (string)null);
                });

            modelBuilder.Entity("TCTVocabulary.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Example")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleTranslation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonetic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetId")
                        .HasColumnType("int")
                        .HasColumnName("SetID");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId")
                        .HasName("PK__Cards__55FECD8E2103FA66");

                    b.HasIndex("SetId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("HasPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__CB1927A0B52422EC");

                    b.HasIndex("OwnerId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("TCTVocabulary.Models.ClassFolder", b =>
                {
                    b.Property<int>("ClassFolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClassFolderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassFolderId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AddedByUserID");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("ClassID");

                    b.Property<int>("FolderId")
                        .HasColumnType("int")
                        .HasColumnName("FolderID");

                    b.HasKey("ClassFolderId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("FolderId");

                    b.HasIndex("ClassId", "FolderId")
                        .IsUnique();

                    b.ToTable("ClassFolders", (string)null);
                });

            modelBuilder.Entity("TCTVocabulary.Models.ClassMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("ClassMessages");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Folder", b =>
                {
                    b.Property<int>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FolderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FolderId"));

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("int")
                        .HasColumnName("ParentFolderID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FolderId")
                        .HasName("PK__Folders__ACD7109F2ECFF2AF");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("UserId");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("TCTVocabulary.Models.LearningProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgressID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardID");

                    b.Property<DateTime?>("LastReviewedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RepetitionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("WrongCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProgressId")
                        .HasName("PK__Learning__BAE29C8531677C23");

                    b.HasIndex("CardId");

                    b.HasIndex(new[] { "UserId", "CardId" }, "UQ__Learning__E2D72075740E222A")
                        .IsUnique();

                    b.ToTable("LearningProgress", (string)null);
                });

            modelBuilder.Entity("TCTVocabulary.Models.Set", b =>
                {
                    b.Property<int>("SetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SetID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SetId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int")
                        .HasColumnName("FolderID");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerID");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SetId")
                        .HasName("PK__Sets__7E08473D47BDA11E");

                    b.HasIndex("FolderId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("SpeakingPlaylists");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingSentence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("EndTime")
                        .HasColumnType("float");

                    b.Property<double>("StartTime")
                        .HasColumnType("float");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<string>("VietnameseMeaning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("SpeakingSentences");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoutubeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("SpeakingVideos");
                });

            modelBuilder.Entity("TCTVocabulary.Models.TCTVocabulary.Models.SavedFolder", b =>
                {
                    b.Property<int>("SavedFolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedFolderId"));

                    b.Property<int>("FolderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SavedFolderId");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId", "FolderId")
                        .IsUnique();

                    b.ToTable("SavedFolders");
                });

            modelBuilder.Entity("TCTVocabulary.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Goal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC46CDCFCA");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534362A84D8")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 16, 20, 51, 117, DateTimeKind.Unspecified),
                            Email = "baochau1512v@gmail.com",
                            FullName = "chau2203",
                            Goal = 0,
                            PasswordHash = "$2a$11$.ryXFi1l5E2Bomp0jygOMuPyhcqbpwpMuOHB79oBcAe9idsouoL6u",
                            Role = "User",
                            Streak = 0
                        });
                });

            modelBuilder.Entity("TCTVocabulary.Models.UserSpeakingProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("float");

                    b.Property<double>("CompletenessScore")
                        .HasColumnType("float");

                    b.Property<double>("FluencyScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("PracticedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SentenceId")
                        .HasColumnType("int");

                    b.Property<double>("TotalScore")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SentenceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSpeakingProgresses");
                });

            modelBuilder.Entity("ClassMember", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Class", "Class")
                        .WithMany("ClassMembers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("ClassMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Card", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Set", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetId")
                        .IsRequired()
                        .HasConstraintName("FK__Cards__SetID__4CA06362");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Class", b =>
                {
                    b.HasOne("TCTVocabulary.Models.User", "Owner")
                        .WithMany("Classes")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Classes__OwnerID__412EB0B6");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TCTVocabulary.Models.ClassFolder", b =>
                {
                    b.HasOne("TCTVocabulary.Models.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCTVocabulary.Models.Class", "Class")
                        .WithMany("ClassFolders")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCTVocabulary.Models.Folder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Class");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("TCTVocabulary.Models.ClassMessage", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Class", "Class")
                        .WithMany("ClassMessages")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("ClassMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Folder", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Folder", "ParentFolder")
                        .WithMany("InverseParentFolder")
                        .HasForeignKey("ParentFolderId")
                        .HasConstraintName("FK__Folders__ParentF__3E52440B");

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("Folders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Folders__UserID__3D5E1FD2");

                    b.Navigation("ParentFolder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.LearningProgress", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Card", "Card")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("CardId")
                        .IsRequired()
                        .HasConstraintName("FK__LearningP__CardI__5441852A");

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__LearningP__UserI__534D60F1");

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Set", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Folder", "Folder")
                        .WithMany("Sets")
                        .HasForeignKey("FolderId")
                        .HasConstraintName("FK__Sets__FolderID__49C3F6B7");

                    b.HasOne("TCTVocabulary.Models.User", "Owner")
                        .WithMany("Sets")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Sets__OwnerID__48CFD27E");

                    b.Navigation("Folder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingSentence", b =>
                {
                    b.HasOne("TCTVocabulary.Models.SpeakingVideo", "SpeakingVideo")
                        .WithMany("SpeakingSentences")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpeakingSentences_SpeakingVideos");

                    b.Navigation("SpeakingVideo");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingVideo", b =>
                {
                    b.HasOne("TCTVocabulary.Models.SpeakingPlaylist", "SpeakingPlaylist")
                        .WithMany("SpeakingVideos")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SpeakingVideos_SpeakingPlaylists");

                    b.Navigation("SpeakingPlaylist");
                });

            modelBuilder.Entity("TCTVocabulary.Models.TCTVocabulary.Models.SavedFolder", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Folder", "Folder")
                        .WithMany("SavedFolders")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("SavedFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.User", b =>
                {
                    b.HasOne("TCTVocabulary.Models.Class", null)
                        .WithMany("Users")
                        .HasForeignKey("ClassId");
                });

            modelBuilder.Entity("TCTVocabulary.Models.UserSpeakingProgress", b =>
                {
                    b.HasOne("TCTVocabulary.Models.SpeakingSentence", "SpeakingSentence")
                        .WithMany("UserSpeakingProgresses")
                        .HasForeignKey("SentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSpeakingProgress_SpeakingSentences");

                    b.HasOne("TCTVocabulary.Models.User", "User")
                        .WithMany("UserSpeakingProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserSpeakingProgress_Users");

                    b.Navigation("SpeakingSentence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Card", b =>
                {
                    b.Navigation("LearningProgresses");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Class", b =>
                {
                    b.Navigation("ClassFolders");

                    b.Navigation("ClassMembers");

                    b.Navigation("ClassMessages");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Folder", b =>
                {
                    b.Navigation("InverseParentFolder");

                    b.Navigation("SavedFolders");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("TCTVocabulary.Models.Set", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingPlaylist", b =>
                {
                    b.Navigation("SpeakingVideos");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingSentence", b =>
                {
                    b.Navigation("UserSpeakingProgresses");
                });

            modelBuilder.Entity("TCTVocabulary.Models.SpeakingVideo", b =>
                {
                    b.Navigation("SpeakingSentences");
                });

            modelBuilder.Entity("TCTVocabulary.Models.User", b =>
                {
                    b.Navigation("ClassMembers");

                    b.Navigation("ClassMessages");

                    b.Navigation("Classes");

                    b.Navigation("Folders");

                    b.Navigation("LearningProgresses");

                    b.Navigation("SavedFolders");

                    b.Navigation("Sets");

                    b.Navigation("UserSpeakingProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
