using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using YoutubeExplode;
using YoutubeExplode.Videos.ClosedCaptions;
using TCTVocabulary.Models;

namespace TCTVocabulary.Services;

public interface IYoutubeTranscriptService
{
    Task<List<SpeakingSentence>> GetTranscriptAsync(string youtubeId);
    Task<YoutubeTranscriptResult> GetTranscriptForSpeakingImportAsync(string youtubeId, CancellationToken ct = default);
    Task<string?> GetVideoDurationAsync(string youtubeId);
    Task<YoutubeVideoMetadata?> GetVideoMetadataAsync(string youtubeId);
}

public sealed record YoutubeTranscriptResult(
    List<SpeakingSentence> Sentences,
    bool IsEnglishUsable,
    string? TranscriptSource);

public sealed record YoutubeVideoMetadata(
    string Title,
    string? ThumbnailUrl);

public class YoutubeTranscriptService : IYoutubeTranscriptService
{
    private const int MinTranscriptSentenceCount = 3;
    private static readonly HashSet<string> CommonEnglishWords =
    [
        "the", "and", "to", "of", "in", "is", "you", "that", "it", "for",
        "on", "with", "as", "this", "be", "are", "was", "have", "at", "or"
    ];

    private readonly YoutubeClient _youtubeClient;
    private readonly IConfiguration _configuration;
    private readonly IHttpClientFactory _httpClientFactory;
    private readonly ILogger<YoutubeTranscriptService> _logger;

    public YoutubeTranscriptService(
        IConfiguration configuration,
        IHttpClientFactory httpClientFactory,
        ILogger<YoutubeTranscriptService> logger)
    {
        _youtubeClient = new YoutubeClient();
        _configuration = configuration;
        _httpClientFactory = httpClientFactory;
        _logger = logger;
    }

    public async Task<List<SpeakingSentence>> GetTranscriptAsync(string youtubeId)
    {
        var result = await GetTranscriptForSpeakingImportAsync(youtubeId);
        return result.Sentences;
    }

    public async Task<YoutubeTranscriptResult> GetTranscriptForSpeakingImportAsync(string youtubeId, CancellationToken ct = default)
    {
        try
        {
            var trackManifest = await _youtubeClient.Videos.ClosedCaptions.GetManifestAsync(youtubeId);

            var trackInfo = trackManifest.TryGetByLanguage("en")
                ?? trackManifest.Tracks.FirstOrDefault(t =>
                    t.Language.Name.Contains("English", StringComparison.OrdinalIgnoreCase));

            if (trackInfo != null)
            {
                _logger.LogInformation("Found closed captions for video {YoutubeId} (auto={IsAuto}).",
                    youtubeId, trackInfo.IsAutoGenerated);
                var track = await _youtubeClient.Videos.ClosedCaptions.GetAsync(trackInfo);
                var captionSentences = ParseClosedCaptions(track, trackInfo.IsAutoGenerated);

                if (IsUsableEnglishTranscript(captionSentences))
                {
                    return new YoutubeTranscriptResult(captionSentences, true, "youtube-captions");
                }
            }

            _logger.LogWarning("No usable English captions found for video {YoutubeId}. Falling back to Gemini.", youtubeId);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to load closed captions for video {YoutubeId}. Falling back to Gemini.", youtubeId);
        }

        var fallbackSentences = await ProcessAudioWithGeminiAsync(youtubeId, ct);
        if (IsUsableEnglishTranscript(fallbackSentences))
        {
            return new YoutubeTranscriptResult(fallbackSentences, true, "gemini-fallback");
        }

        return new YoutubeTranscriptResult(new List<SpeakingSentence>(), false, null);
    }

    public async Task<string?> GetVideoDurationAsync(string youtubeId)
    {
        try
        {
            var video = await _youtubeClient.Videos.GetAsync(youtubeId);
            var duration = video.Duration;

            if (duration == null || duration.Value.TotalSeconds < 1)
                return null;

            var ts = duration.Value;
            return ts.TotalHours >= 1
                ? $"{(int)ts.TotalHours}:{ts.Minutes:D2}:{ts.Seconds:D2}"
                : $"{(int)ts.TotalMinutes}:{ts.Seconds:D2}";
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to get video duration for {YoutubeId}", youtubeId);
            return null;
        }
    }

    public async Task<YoutubeVideoMetadata?> GetVideoMetadataAsync(string youtubeId)
    {
        try
        {
            var video = await _youtubeClient.Videos.GetAsync(youtubeId);
            return new YoutubeVideoMetadata(
                video.Title,
                YoutubeUrlHelper.BuildDefaultThumbnailUrl(youtubeId));
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to get video metadata for {YoutubeId}", youtubeId);
            return null;
        }
    }

    // =========================================================================
    // Caption parsing
    // =========================================================================

    /// <summary>
    /// Parse closed captions thành danh sách SpeakingSentence.
    /// 
    /// - Manual captions: giữ nguyên từng caption chunk (đã formatted sẵn).
    /// - Auto-generated: gộp tất cả chunks thành 1 chuỗi, split tại dấu câu (. ? !),
    ///   rồi map timing từ character offset → caption chunk gốc.
    /// </summary>
    private static List<SpeakingSentence> ParseClosedCaptions(ClosedCaptionTrack track, bool isAutoGenerated)
    {
        if (!isAutoGenerated)
        {
            // ── Manual captions: giữ nguyên từng chunk ──
            var manualSentences = new List<SpeakingSentence>();
            foreach (var caption in track.Captions)
            {
                if (string.IsNullOrWhiteSpace(caption.Text))
                    continue;

                var cleanText = caption.Text.Replace("\n", " ").Replace("\r", "").Trim();
                if (string.IsNullOrWhiteSpace(cleanText))
                    continue;

                manualSentences.Add(new SpeakingSentence
                {
                    StartTime = caption.Offset.TotalSeconds,
                    EndTime = caption.Offset.TotalSeconds + caption.Duration.TotalSeconds,
                    Text = cleanText,
                    VietnameseMeaning = string.Empty
                });
            }
            return manualSentences;
        }

        // ── Auto-generated captions: gộp → split tại dấu câu → map timing ──

        // Bước 1: Thu thập caption chunks
        var chunks = new List<(string Text, double StartTime, double EndTime)>();
        foreach (var caption in track.Captions)
        {
            if (string.IsNullOrWhiteSpace(caption.Text))
                continue;

            var cleanText = caption.Text.Replace("\n", " ").Replace("\r", "").Trim();
            if (string.IsNullOrWhiteSpace(cleanText))
                continue;

            chunks.Add((
                cleanText,
                caption.Offset.TotalSeconds,
                caption.Offset.TotalSeconds + caption.Duration.TotalSeconds));
        }

        if (chunks.Count == 0)
            return [];

        // Bước 2: Gộp thành 1 chuỗi + build character → timing mapping
        //   charTimings[i] = (startTime, endTime) của caption chunk chứa ký tự tại vị trí i
        var merged = new StringBuilder();
        var charTimings = new List<(double StartTime, double EndTime)>();

        for (var i = 0; i < chunks.Count; i++)
        {
            if (i > 0)
            {
                merged.Append(' ');
                // Space giữa các chunk: gán timing của chunk trước
                charTimings.Add((chunks[i - 1].StartTime, chunks[i - 1].EndTime));
            }

            foreach (var ch in chunks[i].Text)
            {
                merged.Append(ch);
                charTimings.Add((chunks[i].StartTime, chunks[i].EndTime));
            }
        }

        var fullText = merged.ToString();

        // Bước 3: Split tại dấu kết thúc câu (. ? !) — giữ dấu câu trong câu
        var sentenceTexts = Regex.Split(fullText, @"(?<=[.!?])\s+")
            .Select(s => s.Trim())
            .Where(s => !string.IsNullOrWhiteSpace(s))
            .ToList();

        if (sentenceTexts.Count == 0)
        {
            // Không có dấu câu nào → trả toàn bộ text như 1 câu duy nhất
            return
            [
                new SpeakingSentence
                {
                    StartTime = chunks[0].StartTime,
                    EndTime = chunks[^1].EndTime,
                    Text = fullText,
                    VietnameseMeaning = string.Empty
                }
            ];
        }

        // Bước 4: Map timing — tìm vị trí từng câu trong fullText → lấy timing
        var sentences = new List<SpeakingSentence>();
        var searchFrom = 0;

        foreach (var sentenceText in sentenceTexts)
        {
            var startIdx = fullText.IndexOf(sentenceText, searchFrom, StringComparison.Ordinal);
            if (startIdx < 0)
                startIdx = searchFrom; // fallback

            var endIdx = Math.Min(startIdx + sentenceText.Length - 1, charTimings.Count - 1);
            startIdx = Math.Min(startIdx, charTimings.Count - 1);

            var startTime = charTimings[startIdx].StartTime;
            var endTime = charTimings[endIdx].EndTime;

            sentences.Add(new SpeakingSentence
            {
                StartTime = startTime,
                EndTime = endTime,
                Text = sentenceText,
                VietnameseMeaning = string.Empty
            });

            searchFrom = endIdx + 1;
        }

        return sentences;
    }

    // =========================================================================
    // Gemini audio fallback (khi không có caption nào)
    // =========================================================================

    private async Task<List<SpeakingSentence>> ProcessAudioWithGeminiAsync(string youtubeId, CancellationToken ct)
    {
        var apiKey = _configuration["AI:ApiKey"]
            ?? _configuration["Ai:ApiKey"]
            ?? _configuration["Gemini:ApiKey"];

        if (string.IsNullOrWhiteSpace(apiKey))
        {
            _logger.LogWarning("Gemini API key is missing. Fallback skipped for video {YoutubeId}.", youtubeId);
            return new List<SpeakingSentence>();
        }

        var streamManifest = await _youtubeClient.Videos.Streams.GetManifestAsync(youtubeId);
        var audioStreamInfo = streamManifest.GetAudioOnlyStreams().OrderBy(s => s.Bitrate).FirstOrDefault();
        if (audioStreamInfo == null)
        {
            _logger.LogWarning("No audio streams available for video {YoutubeId}.", youtubeId);
            return new List<SpeakingSentence>();
        }

        await using var memoryStream = new MemoryStream();
        await _youtubeClient.Videos.Streams.CopyToAsync(audioStreamInfo, memoryStream);

        var audioBytes = memoryStream.ToArray();
        var audioBase64 = Convert.ToBase64String(audioBytes);
        var mimeType = audioStreamInfo.Container.Name == "mp4" ? "audio/mp4" : "audio/webm";

        var model = _configuration["AI:Model"] ?? "gemini-2.5-flash-lite";
        var baseUrl = (_configuration["AI:BaseUrl"] ?? "https://generativelanguage.googleapis.com/v1beta").TrimEnd('/');
        var endpoint = $"{baseUrl}/models/{model}:generateContent?key={Uri.EscapeDataString(apiKey)}";

        var payloadJson = JsonSerializer.Serialize(new
        {
            contents = new[]
            {
                new
                {
                    role = "user",
                    parts = new object[]
                    {
                        new { text = "Transcribe this audio in English only. Return plain transcript text only, no markdown, no translation, no explanation." },
                        new { inline_data = new { mime_type = mimeType, data = audioBase64 } }
                    }
                }
            },
            generationConfig = new
            {
                temperature = 0.1,
                maxOutputTokens = 8192
            }
        });

        var client = _httpClientFactory.CreateClient();
        client.Timeout = TimeSpan.FromMinutes(5);

        using var request = new HttpRequestMessage(HttpMethod.Post, endpoint)
        {
            Content = new StringContent(payloadJson, Encoding.UTF8, "application/json")
        };

        using var response = await client.SendAsync(request, ct);
        if (!response.IsSuccessStatusCode)
        {
            _logger.LogWarning("Gemini fallback failed for video {YoutubeId} with status {StatusCode}.", youtubeId, (int)response.StatusCode);
            return new List<SpeakingSentence>();
        }

        var responseBody = await response.Content.ReadAsStringAsync(ct);
        var transcriptText = ParseGeminiTranscriptText(responseBody);
        if (string.IsNullOrWhiteSpace(transcriptText))
        {
            return new List<SpeakingSentence>();
        }

        var durationSeconds = await GetVideoDurationSecondsAsync(youtubeId);
        return BuildTimedSentences(transcriptText, durationSeconds);
    }

    private async Task<double> GetVideoDurationSecondsAsync(string youtubeId)
    {
        try
        {
            var video = await _youtubeClient.Videos.GetAsync(youtubeId);
            return Math.Max(video.Duration?.TotalSeconds ?? 0, 1);
        }
        catch
        {
            return 120;
        }
    }

    private static string ParseGeminiTranscriptText(string responseBody)
    {
        try
        {
            using var document = JsonDocument.Parse(responseBody);
            var root = document.RootElement;

            if (!root.TryGetProperty("candidates", out var candidates) || candidates.GetArrayLength() == 0)
            {
                return string.Empty;
            }

            var parts = candidates[0]
                .GetProperty("content")
                .GetProperty("parts")
                .EnumerateArray()
                .Select(part => part.TryGetProperty("text", out var textNode) ? textNode.GetString() : null)
                .Where(text => !string.IsNullOrWhiteSpace(text))
                .Select(text => text!.Trim())
                .ToList();

            return string.Join("\n", parts);
        }
        catch
        {
            return string.Empty;
        }
    }

    private static List<SpeakingSentence> BuildTimedSentences(string transcriptText, double durationSeconds)
    {
        var segments = Regex.Split(transcriptText, @"(?<=[.!?])\s+")
            .Select(segment => segment.Trim())
            .Where(segment => !string.IsNullOrWhiteSpace(segment))
            .ToList();

        if (segments.Count == 0)
        {
            return new List<SpeakingSentence>();
        }

        var totalWords = segments
            .Select(segment => segment.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length)
            .Sum();

        var currentStart = 0d;
        var sentences = new List<SpeakingSentence>(segments.Count);

        foreach (var segment in segments)
        {
            var words = Math.Max(segment.Split(' ', StringSplitOptions.RemoveEmptyEntries).Length, 1);
            var ratio = totalWords == 0 ? 1d / segments.Count : (double)words / totalWords;
            var estimatedDuration = Math.Max(durationSeconds * ratio, 1.2);
            var end = Math.Min(currentStart + estimatedDuration, durationSeconds);

            sentences.Add(new SpeakingSentence
            {
                StartTime = currentStart,
                EndTime = end,
                Text = segment,
                VietnameseMeaning = string.Empty
            });

            currentStart = end;
        }

        return sentences;
    }

    // =========================================================================
    // Validation helpers
    // =========================================================================

    private static bool IsUsableEnglishTranscript(List<SpeakingSentence> sentences)
    {
        if (sentences.Count < MinTranscriptSentenceCount)
        {
            return false;
        }

        var merged = string.Join(" ", sentences.Select(s => s.Text));
        return LooksLikelyEnglish(merged);
    }

    private static bool LooksLikelyEnglish(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return false;
        }

        var lowered = text.ToLowerInvariant();
        var tokens = Regex.Split(lowered, @"\W+")
            .Where(token => token.Length > 0)
            .ToList();

        if (tokens.Count < 20)
        {
            return false;
        }

        var englishTokenHits = tokens.Count(token => CommonEnglishWords.Contains(token));
        if (englishTokenHits < 3)
        {
            return false;
        }

        var asciiLetterCount = lowered.Count(ch => ch is >= 'a' and <= 'z');
        return asciiLetterCount >= lowered.Length * 0.55;
    }
}
